CREATE TABLE {schema}.companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text,
    name text NOT NULL CHECK (length(trim(name)) > 0),
    sector text,
    description text,
    categories jsonb,
    folder_exists boolean NOT NULL DEFAULT false,
    exchange text,
    cik text,
    fiscal_year_end text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE {schema}.metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_key text NOT NULL UNIQUE CHECK (length(trim(metric_key)) > 0),
    display_name text NOT NULL CHECK (length(trim(display_name)) > 0),
    description text,
    value_type text NOT NULL CHECK (value_type IN
        ('currency','percent','ratio','count','per_share','days','multiple','other')),
    measurement_basis text CHECK (measurement_basis IN ('duration','instant')),
    unit_convention text CHECK (unit_convention IN
        ('base_currency','base_currency_per_share','fraction','ratio','count','days','multiple','defined_unit')),
    entity_scope text CHECK (length(trim(entity_scope)) > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE {schema}.company_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES {schema}.companies(id),
    period_kind text NOT NULL CHECK (period_kind IN ('quarter','year','ytd')),
    fiscal_year integer NOT NULL,
    fiscal_quarter integer CHECK (fiscal_quarter BETWEEN 1 AND 4),
    fiscal_label text NOT NULL CHECK (length(trim(fiscal_label)) > 0),
    period_start date,
    period_end date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (period_start IS NULL OR period_start <= period_end),
    CHECK (period_kind != 'quarter' OR fiscal_quarter IS NOT NULL),
    CHECK (period_kind != 'year' OR fiscal_quarter IS NULL),
    CONSTRAINT period_identity UNIQUE NULLS NOT DISTINCT
        (company_id, period_kind, period_start, period_end)
);
CREATE TABLE {schema}.sources (
    id uuid PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES {schema}.companies(id),
    reference text NOT NULL CHECK (length(trim(reference)) > 0),
    url text,
    published_on date,
    retrieved_at timestamptz,
    content_sha256 text CHECK (content_sha256 ~ '^[a-f0-9]{{64}}$'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, reference)
);
CREATE TABLE {schema}.metric_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id bigint NOT NULL REFERENCES {schema}.metrics(id),
    period_id bigint NOT NULL REFERENCES {schema}.company_periods(id),
    value numeric CHECK (value::text NOT IN ('NaN','Infinity','-Infinity')),
    value_high numeric CHECK (value_high::text NOT IN ('NaN','Infinity','-Infinity')),
    value_status text NOT NULL DEFAULT 'valid' CHECK (value_status IN
        ('valid','unavailable','not_disclosed','not_applicable','unreadable')),
    qualifier text NOT NULL DEFAULT 'exact' CHECK (qualifier IN
        ('exact','approx','gt','gte','lt','lte','range')),
    scenario text NOT NULL DEFAULT 'actual' CHECK (scenario IN
        ('actual','guidance','target','consensus','estimate')),
    origin text NOT NULL DEFAULT 'reported' CHECK (origin IN ('reported','derived')),
    currency_code text,
    reported_text text,
    source_ref text,
    source_id uuid REFERENCES {schema}.sources(id),
    source_locator text,
    calculation_note text,
    verification_status text NOT NULL DEFAULT 'unverified' CHECK
        (verification_status IN ('legacy_unverified','unverified','source_verified')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (value_status != 'valid' OR value IS NOT NULL),
    CHECK ((qualifier = 'range' AND value IS NOT NULL AND value_high IS NOT NULL AND value_high >= value)
        OR (qualifier != 'range' AND value_high IS NULL)),
    CHECK (origin != 'reported' OR NULLIF(trim(source_ref), '') IS NOT NULL),
    CHECK (origin != 'derived' OR NULLIF(trim(calculation_note), '') IS NOT NULL),
    CHECK (verification_status != 'source_verified' OR
        (source_id IS NOT NULL AND NULLIF(trim(source_locator), '') IS NOT NULL)),
    UNIQUE (metric_id, period_id, scenario)
);
CREATE INDEX metric_history ON {schema}.metric_values (metric_id, scenario, period_id);
CREATE VIEW {schema}.metric_values_flat AS
SELECT v.*, p.company_id, c.ticker, c.name AS company_name,
    m.metric_key, m.display_name AS metric_name, m.value_type, m.measurement_basis,
    m.unit_convention, m.entity_scope,
    p.period_kind, p.fiscal_year, p.fiscal_quarter, p.fiscal_label,
    p.period_start, p.period_end, s.url AS source_url, s.published_on,
    s.retrieved_at, s.content_sha256
FROM {schema}.metric_values v
JOIN {schema}.company_periods p ON p.id = v.period_id
JOIN {schema}.companies c ON c.id = p.company_id
JOIN {schema}.metrics m ON m.id = v.metric_id
LEFT JOIN {schema}.sources s ON s.id = v.source_id;
