[project]
name = "earnings_digest"
version = "0.1.0"
description = "earnings-digest using crewAI"
authors = [
    { name = "Your Name", email = "you@example.com" },
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.95.0,<1.0.0",
    "pymongo>=4.10.0"
]

[project.scripts]
earnings_digest = "earnings_digest.main:run"
run_crew = "earnings_digest.main:run"
train = "earnings_digest.main:train"
replay = "earnings_digest.main:replay"
test = "earnings_digest.main:test"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
